# Generated by Django 4.1.5 on 2023-02-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='токен верификации'),
        ),
    ]
