# Generated by Django 4.1.5 on 2023-02-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursach', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('deactivate', 'Can deactivate mailing')]},
        ),
    ]
